// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enableBionicReader": boolean;
      "disableForLanguages": string;
      "enableReaderToolbarButton": boolean;
      "enableSoftPaperTheme": boolean;
      "enableStructureWordColors": boolean;
      "enableCustomTermColors": boolean;
      "customHighlightTerms": string;
      "bionicIntensity": string;
      "bionicContrastMode": string;
      "opacityContrast": number;
      "weightContrast": number;
      "weightOffset": number;
      "parsingOffset": number;
    };
  }
}
